### ISSUE TITLE
APK install doesn't work

### ISSUE THREAD

**Issue by Kedlub** [AmazMod/AmazMod#327]
I tried to install it with the "send to watch" option on apk's and also with file manager inside the app, but it simply doesn't work, phone app says it started to install but it never finishes on the watch.
I tried it with the latest stable version and also with the latest commit on dev, but it doesn't work with either.

What could be the problem?

**Comment by lfom** [comment]
It does work, at least with latest dev... Maybe the APK you are trying to install is broken? If you are sure it isn't, please attach a logcat from watch filtered using "amazmod" or there is little that can be done...

**Comment by Kedlub** [comment]
Well, I tried it with multiple APKs that work fine when installed through adb, so it's not that they're broken.
And here's the log
[logcat.txt](https://github.com/AmazMod/AmazMod/files/2664288/logcat.txt)

Also if it helps, I'm using international Amazfit Pace on stock firmware 2.8.1.0

**Comment by lfom** [comment]
@Kedlub thanks for the logcat. It seems the install script isn't running at all. I have seen this on custom ROMs with non-stock busybox only. Could you please paste the output of the commands bellow here?

`busybox | grep binary
busybox | grep sh`

**Comment by Kedlub** [comment]
Ok, here's the output:

busybox | grep binary
BusyBox v1.21.1 (2013-07-08 11:09:23 CDT) multi-call binary.
        BusyBox is a multi-call binary that combines many common Unix

busybox | grep sh
        link to busybox for each function they wish to use and BusyBox
        [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash,
        expand, expr, fakeidentd, false, fbset, fbsplash, fdflush, fdformat,
        hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave,
        remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm,
        setkeycodes, setlogcons, setserial, setsid, setuidgid, sh, sha1sum,
        sha256sum, sha3sum, sha512sum, showkey, slattach, sleep, smemcap,

**Comment by lfom** [comment]
Pushed a new commit today to dev branch today, please test and provide a logcat, if possible.

**Comment by lfom** [comment]
@Kedlub Yeah, it seems that there are some differences when building on Mac and on PC, today @fcaronte helped and I could test via remote access, should work now with the latest commit. Please confirm.

**Comment by Kedlub** [comment]
Still nothing, it threw another syntax error
`/data/data/com.amazmod.service/files/install_apk.sh[53]: syntax error: 'if' unmatched `
Here's logcat: [logcat.txt](https://github.com/AmazMod/AmazMod/files/2674687/logcat.txt)

**Comment by lfom** [comment]
Are you use you have the latest code? Please try re-installing service APK or clear its data, the latest code works for other people as well, not just me.

**Comment by Kedlub** [comment]
Yes, I'm using the latest version.
I tried to reinstall it, clear data, update my android studio, redownload the project, but it still throws that error.
So it seems there is something wrong with my computer or watch.

**Comment by Kedlub** [comment]
Found the problem and it works now 😄 
It turned out that the syntax error was caused by my android studio converting line endings from LF to CRLF.
Thanks for helping.

**Comment by fcaronte** [comment]
Thank so much  @Kedlub!!! finally work for me too!!
